INSERT INTO cdc_catalog.runtime_config (config_key, component, conn_id, config_value, description) VALUES
    ('apply_max_seconds', 'cdc_kafka_apply', '', '300'::jsonb, 'Max seconds per apply slice (test: 60 via reset_kafka_topics.sh --test-runtime)'),
    ('apply_max_events', 'cdc_kafka_apply', '', '10000000'::jsonb, 'Max Kafka events per apply slice'),
    ('apply_target_events_per_table', 'cdc_kafka_apply', '', '0'::jsonb, 'Per-table soft cap per slice; 0 = unlimited (drain Kafka as fast as PG allows)'),
    ('apply_max_table_staleness_seconds', 'cdc_kafka_apply', '', '900'::jsonb, 'Table stale threshold if last_applied_at exceeds this'),
    ('apply_batch_size', 'cdc_kafka_apply', '', '50000'::jsonb, 'Kafka events buffered before PG flush (COPY batch)'),
    ('apply_mode', 'cdc_kafka_apply', '', '"copy"'::jsonb, 'Lake apply: copy (bulk COPY) or row (per-event upsert)'),
    ('apply_copy_format', 'cdc_kafka_apply', '', '"binary"'::jsonb, 'COPY format: binary (auto-fallback csv) or csv'),
    ('apply_append_only', 'cdc_kafka_apply', '', 'true'::jsonb, 'Direct COPY append for insert-only ops'),
    ('apply_audit_enabled', 'cdc_kafka_apply', '', 'true'::jsonb, 'Batch cdc_applied_events audit'),
    ('apply_dedup_enabled', 'cdc_kafka_apply', '', 'true'::jsonb, 'Filter already-applied event_ids'),
    ('apply_poll_timeout_ms', 'cdc_kafka_apply', '', '100'::jsonb, 'Kafka consumer poll timeout ms'),
    ('apply_fetch_max_bytes', 'cdc_kafka_apply', '', '52428800'::jsonb, 'Kafka fetch.max.bytes'),
    ('apply_max_partition_fetch_bytes', 'cdc_kafka_apply', '', '10485760'::jsonb, 'Kafka max.partition.fetch.bytes'),
    ('apply_quarantine_max_failures', 'cdc_kafka_apply', '', '5'::jsonb, 'Consecutive apply failures before quarantine'),
    ('capture_lag_warning_seconds', 'cdc_kafka_health', '', '300'::jsonb, 'Capture lag WARNING threshold'),
    ('capture_lag_critical_seconds', 'cdc_kafka_health', '', '1800'::jsonb, 'Capture lag CRITICAL threshold'),
    ('binlog_retention_headroom_warning_hours', 'cdc_kafka_health', '', '24'::jsonb, 'Warn when capture lag consumes this much of binlog retention'),
    ('kafka_bootstrap_servers', 'cdc_kafka_apply', '', '"localhost:9092"'::jsonb, 'Kafka bootstrap servers'),
    ('kafka_consumer_group', 'cdc_kafka_apply', '', '"datalake-cdc-apply"'::jsonb, 'Kafka consumer group for apply service'),
    ('debezium_topic_prefix', 'cdc_kafka_apply', '', '"MARIADB_LOCAL"'::jsonb, 'Debezium topic.prefix / conn_id'),
    ('debezium_connect_url', 'cdc_kafka_health', '', '"http://localhost:8083"'::jsonb, 'Kafka Connect REST API'),
    ('debezium_connector_name', 'cdc_kafka_health', '', '"datalake-mariadb-local"'::jsonb, 'Debezium connector name')
ON CONFLICT (config_key, component, conn_id) DO NOTHING;
